export const Projects = [
  {
    name: "umutk.me",
    description: "Simple Portfolio Website",
    language: "Typescript",
    link: "https://github.com/UmutKDev/umutk.me",
    color: "#2778ca",
  },
  {
    name: "Auth App",
    description: "Nestjs JWT Passport Auth With React",
    language: "Typescript",
    link: "https://github.com/UmutKDev/nestjs-auth-with-react",
    color: "#2778ca",
  },
  {
    name: "Astrology API",
    description: "Astrology API with Nest.js",
    language: "Typescript",
    link: "https://github.com/UmutKDev/astrology-api",
    color: "#2778ca",
  },
  {
    name: "Paraharca",
    description: "Spend your money",
    language: "Typescript",
    link: "https://github.com/UmutKDev/paraharca",
    color: "#2778ca",
  },
  {
    name: "8Ball",
    description: "Question and Answer Game",
    language: "Javascript",
    link: "https://github.com/UmutKDev/8ball",
    color: "#ecd932",
  },
  {
    name: "Quick Feels Good",
    description: "Simple feeling app",
    language: "Javascript",
    link: "https://github.com/UmutKDev/quickfeelsgood",
    color: "#ecd932",
  },
  {
    name: "Minecraft Skin Finder",
    description: "A Simple Minecraft Skin Finder",
    language: "Typescript",
    color: "#2778ca",
    link: "https://github.com/UmutKDev/minecraft-skin-finder",
  },
];
